// app/layout.tsx

import type { Metadata } from "next";
import { Inter } from "next/font/google"; // Import Google font
import "./globals.css";
import { ClerkProvider, SignedIn, SignedOut } from "@clerk/nextjs"; // Clerk imports
import { ToasterProvider } from "@/components/providers/toaster-provider"; // Toaster notifications
import Intro from "@/components/page"; // Import your Intro component

// Use the Inter font
const inter = Inter({ subsets: ["latin"] });

// Metadata for the app
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <ToasterProvider />

          
          <SignedIn>
            {children}
          </SignedIn>

        
          <SignedOut>
            <Intro />
          </SignedOut>

        </body>
      </html>
    </ClerkProvider>
  );
}
